#!/usr/bin/env zsh

if [ ! -f ~/.ifttt ]; then
    echo 'Error! Please add your IFTTT Webhooks Token to ~/.ifttt'
    exit 1
fi

IFTTT_API="https://maker.ifttt.com/trigger/script/with/key/$(cat ~/.ifttt)"

_ifttt_data () {
cat <<-EOF
	{"value1":"$(hostname)","value2":"$(pwd)","value3":"$@"}
EOF
}

ifttt () {
   _ifttt_data "$@" | curl -s -H 'Content-Type: application/json' -o /dev/null -d @- "$IFTTT_API"
}


ifttt "$@"
