#!/usr/bin/env zsh

escape_tmux() { printf '\033Ptmux;\033%s\033\\' "$1" }

sequence="$(printf '\033]777;notify;%s;%s\a' "${1}" "${2}")"

case ${TERM-} in
    screen*)
        escape_tmux "${sequence}" ;;
    tmux*)
        escape_tmux "${sequence}" ;;
    *)
        echo "${sequence}" ;;
esac
