#!/bin/sh

if [ ! -f ~/.ifttt ]; then
    echo 'Error! Please add your IFTTT Webhooks Token to ~/.ifttt'
    exit 1
fi

curl -s -H 'Content-Type: application/json' -o /dev/null -d @- \
    https://maker.ifttt.com/trigger/script/with/key/$(cat ~/.ifttt) <<-EOF
    {"value1":"$(hostname)","value2":"$(pwd)","value3":"$@"}
EOF
